### ISSUE TITLE
Koa <-> Express integration

### ISSUE THREAD

**Issue by bttmly** [koajs/examples#104]
While the Koa docs specifically say that setting `ctx.respond` to `false` is not a supported pattern, it is necessary for embedding a Koa application into a large Express application -- the use case is incrementally moving routes from Express/Connect style to Koa. I'm curious if you're open to adding an example here of how to do that, because it can be a little tricky and there are several pitfalls. As a reference example I put together this repo: https://github.com/bttmly/koa-within-express

But I think it could be useful here for others looking for an Express to Koa migration path!

**Comment by jonathanong** [comment]
i don't think we should offically support it. my strategy would be by using the strangler pattern to create framework-agnostic services, then rebuilt it in koa. though tbh I wouldn't bother migrating from express to koa

**Comment by bttmly** [comment]
well, your mileage may vary, but we did it successfully a couple years ago using `ctx.respond = false`, after [this patch](https://github.com/koajs/koa/commit/e6539e1cf28e5cb5418d9dd3c364c03198610cf1) landed and it ended up working great.
