### ISSUE TITLE
Best place to add the following resources?

### ISSUE THREAD

**Issue by mjhea0** [koajs/examples#116]
Can I add these links to this repo?

1. [Building a RESTful API with Koa and Postgres](http://mherman.org/blog/2017/08/23/building-a-restful-api-with-koa-and-postgres)
1. [User Authentication with Passport and Koa](http://mherman.org/blog/2018/01/02/user-authentication-with-passport-and-koa)

**Comment by kevinrambaud** [comment]
Hey @mjhea0 ! What about adding a new section in the Readme such as "Articles" ?

**Comment by mjhea0** [comment]
Will do @kevinrambaud. Thank you.

**Comment by mjhea0** [comment]
https://github.com/koajs/examples/pull/118
