### ISSUE TITLE
Update koa-router and swig

### ISSUE THREAD

**Issue by septatrix** [koajs/examples#138]
Both packages are currently unmaintained.

Koa-router has already been forked by us and is available as `@koa/router`.
Swig has been forked too and undergoes some further development as `swig-templates`.

These two forks aren't under to much development either and more or less stale but using `@koa/router` gives us a bit more control and `swig-templates` already fixed some bugs and has more up-to-date dependencies (which `npm audit` will  tell you).
I haven't bothered looking into the other packages but these two I think should get updated...

**Comment by jonathanong** [comment]
@septatrix thanks!
