### ISSUE TITLE
404 - no correct 404 page for exceptions in downstream middleware 

### ISSUE THREAD

**Issue by i-erokhin** [koajs/examples#83]
In the example, custom 404 works only if no response from any downstream middleware.

Нowever, if any downstream middleware throws an exception, **pageNotFound()** middleware don't works (default 404 page will be sent).

See my pull request with a test (currently broken): <https://github.com/koajs/examples/pull/82/files>

**Comment by hemanth** [comment]
Even with `exception` and `ok` being seprate middlewares?

**Comment by i-erokhin** [comment]
**ok()** middleware and **'when GET /ok'** is just additional tests for ensure what normal pages works as expected.

**Comment by i-erokhin** [comment]
Obviously, code after ``yield next`` will not works then exception throws in ``next()``.

```javascript
app.use(function *pageNotFound(next){
  yield next;

  if (404 != this.status) return;

  // we need to explicitly set 404 here
  // so that koa doesn't assign 200 on body=
  this.status = 404;

  switch (this.accepts('html', 'json')) {
    case 'html':
      this.type = 'html';
      this.body = '<p>Page Not Found</p>';
      break;
    case 'json':
      this.body = {
        message: 'Page Not Found'
      };
      break;
    default:
      this.type = 'text';
      this.body = 'Page Not Found';
  }
})
```

**Comment by hemanth** [comment]
> explicitly set 404 here
^ SGTM

**Comment by i-erokhin** [comment]
This is not my code, this is the code from the example: https://github.com/koajs/examples/blob/master/404/app.js , and it not works as expected. Or do you think that the code is correct?

**Comment by bananaappletw** [comment]
Sorry to say.
But, I think you are not correct.
Usually, 404 page is place at the end of middleware.
When no route is matched, it show the 404 page.
Or you don't specify the error page, the koa will deal it automatically.
Default, koa set status code as 404.
https://github.com/koajs/koa/blob/master/lib/application.js#L133
In this line https://github.com/koajs/koa/blob/master/lib/application.js#L219
using [statuse](https://github.com/jshttp/statuses) to get message
[get message()](https://github.com/koajs/koa/blob/master/lib/response.js#L95)

**Comment by bananaappletw** [comment]
And, actually your code is not corresponded with what you say.
Your code doesn't throw exception.
In usual, if you throw exception.
Your http status code should be 5xx.
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_Error

**Comment by hemanth** [comment]
Thank you.
