### ISSUE TITLE
[Suggestion] Add coding style check

### ISSUE THREAD

**Issue by bananaappletw** [koajs/examples#89]
Maybe adding coding styles check for this repo could make the example codes coherence.
Just some suggestion.
See also:
https://github.com/koajs/koa/blob/v2.x/.eslintrc.yml
https://github.com/feross/standard

**Comment by bananaappletw** [comment]
@hemanth What do you think about this?
In general, most of rules could be accepted by js programmer.
But there is still a fierce debate about semicolon.
I don't have bias against these two different coding style.
One is with semicolon, the other isn't.
Although, it required better understanding about statements to write code without semicolon.
But mostly, code with semicolon could avoid more errors than one without it.
I think that's why koa is using one with semicolon.

**Comment by hemanth** [comment]
Makes absolute sense, please add them.

**Comment by bananaappletw** [comment]
Sure!!!
But I have some homework to do this week.
Maybe next week, I will have time to implement it.
Thanks for the reply. 😄
