### ISSUE TITLE
update examples to koa@2

### ISSUE THREAD

**Issue by DoumanAsh** [koajs/examples#97]
While studying koajs capabilities i made some REST API by using latest koa.
The question are examples, in this repo, should consist of next version yet or until official release only koa1?

About my code https://github.com/DoumanAsh/lazy-http-can
This repo consist of simple REST service that allows you to test HTTP requests.
There are several things:
* ETag usage (without 3pp lib)
* Example when bypassing koa `ctx.response` might be cool :) https://github.com/DoumanAsh/lazy-http-can/blob/master/server/router.js#L44-L45
* Different kinds of responses (text, files, streams)
* Delayed response
* Usage of koa-better-router (mostly the only 3pp middle-ware i decided to use)

**Comment by bananaappletw** [comment]
@DoumanAsh Hi, I just created [koa2-example](https://github.com/bananaappletw/koa2-examples). 
I will try to migrate koa examples to koa2 in my available time.

**Comment by coderhaoxin** [comment]
I'll update all examples to `koa@2` next weekend :)

Also, PRs welcome! 😄

**Comment by bananaappletw** [comment]
@coderhaoxin Hi, I already migrate some examples.
You could setup the initial process of migrating this repo to koa@2 (babel, eslint ......).
Then I could send the pull request for the examples I migrated.
Thanks for the enhancement of this repo.

**Comment by bananaappletw** [comment]
@coderhaoxin Or, you want to remain the this repo for koa1.
I could transfer my current [repo](https://github.com/bananaappletw/koa2-examples) (already migrate some examples for koa2) to koa organization.
And continue my migration work on koa organization.
What do you think about it?

**Comment by coderhaoxin** [comment]
I'd rather just create a branch such as `koa-v1` for `koa@v1` :)

@bananaappletw 👍 
Feel free to submit PRs to `master` for your migration. ((>_<))

**Comment by bananaappletw** [comment]
@coderhaoxin Could you create `koa-v1` branch in this repo?
Just copy current master to `koa-v1`.
I don't have privilege to do that.
Then, I send the pull request to master.
Thanks.

**Comment by coderhaoxin** [comment]
> Could you create koa-v1 branch in this repo?

DONE :)

**Comment by coderhaoxin** [comment]
50bcadf73e3f61278dbee08a7b10183f32a206c8
